-- 允许所有用户在数据库上创建对象
GRANT CREATE ON DATABASE Hasura TO PUBLIC;

-- 允许所有用户使用 public 模式
GRANT USAGE ON SCHEMA public TO PUBLIC;

-- 允许所有用户在 public 模式中创建对象
GRANT CREATE ON SCHEMA public TO PUBLIC;

-- 赋予所有表的所有权限
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO PUBLIC;

-- 赋予所有序列的所有权限
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO PUBLIC;

-- 设置默认权限
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO PUBLIC;