# 运行命令docker build --pull -t 项目名字-yarn-cache:latest .   这里也可以去cachebuild.sh里更改
FROM node:20.11.0
# ENV HTTP_PROXY=http://192.168.1.4:7890
# ENV HTTPS_PROXY=http://192.168.1.4:7890
RUN mkdir /app
ADD . /app
# 配置 yarn 使用淘宝镜像
RUN yarn config set registry https://registry.npmmirror.com

WORKDIR /app
RUN yarn

WORKDIR /
RUN rm -Rf /app
